# Generated by Django 3.0.7 on 2021-04-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='om', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='choose',
            field=models.CharField(choices=[('Supplier', 'Supplier'), ('Buyer', 'Buyer')], default='Supplier', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='products',
            field=models.CharField(choices=[('Pen', 'Pen'), ('NoteBook', 'NoteBook')], max_length=15, null=True),
        ),
    ]
