# Generated by Django 3.0.7 on 2021-04-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quantity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
