# Generated by Django 3.0.7 on 2021-04-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_user_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='packaging',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
    ]
