# Generated by Django 3.0.7 on 2021-04-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_user_packaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(default='2021-04-27'),
        ),
    ]
