# Generated by Django 3.0.7 on 2021-04-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='images',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
