# Generated by Django 3.0.7 on 2021-04-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_user_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sr_number',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
